"""
Env vars to use on production-like environments (DEV/ON-DEMAND/STAGE/PROD)
"""

print('Loading envs/production')

from os import environ, getenv

MANDRILL_API_KEY = environ['MANDRILL_API_KEY']
MANDRILL_SUBACCOUNT = environ['MANDRILL_SUBACCOUNT']

PAYMENT_STRIPE_PUBLIC_KEY = environ['PAYMENT_STRIPE_PUBLIC_KEY']
PAYMENT_STRIPE_SECRET_KEY = environ['PAYMENT_STRIPE_SECRET_KEY']
PAYMENT_STRIPE_WEBHOOK_SECRET = environ['PAYMENT_STRIPE_WEBHOOK_SECRET']

SES_AIM_KEY_ID = environ['SES_AIM_KEY_ID']
SES_AIM_SECRET_KEY = environ['SES_AIM_SECRET_KEY']

AWS_METADATA_URL = getenv('AWS_METADATA_URL', 'http://169.254.169.254/latest/meta-data/local-ipv4')
S3_BUCKET_NAME = environ['S3_BUCKET_NAME']
S3_BUCKET_AIM_KEY_ID = environ['S3_BUCKET_AIM_KEY_ID']
S3_BUCKET_AIM_SECRET_KEY = environ['S3_BUCKET_AIM_SECRET_KEY']
DJANGO_S3_STATIC = getenv('DJANGO_S3_STATIC')

GOOGLE_MAPS_API_KEY = environ['GMAPS_API_KEY']

SALESFORCE_USERNAME = environ['SALESFORCE_USERNAME']
SALESFORCE_PASSWORD = environ['SALESFORCE_PASSWORD']
SALESFORCE_TOKEN = environ['SALESFORCE_TOKEN']
IS_SALESFORCE_SANDBOX = environ['IS_SALESFORCE_SANDBOX'] != "False"
SALESFORCE_ENABLED = environ['SALESFORCE_ENABLED'] != 'False'

YELP_API_KEY = environ['YELP_API_KEY']

DJANGO_SENTRY_URL = getenv('DJANGO_SENTRY_URL')
DJANGO_SENTRY_ENV = getenv('DJANGO_SENTRY_ENV', 'unset')

LOGSTASH_HOST = getenv('LOGSTASH_HOST')
LOGSTASH_PORT = getenv('LOGSTASH_PORT')

AUTH_FACEBOOK_CLIENT = getenv('AUTH_FACEBOOK_CLIENT')
AUTH_FACEBOOK_SECRET = getenv('AUTH_FACEBOOK_SECRET')

TWILIO_ACCOUNT = getenv('TWILIO_ACCOUNT')
TWILIO_API_KEY = getenv('TWILIO_API_KEY')
TWILIO_CLEANING_REMINDER_MESSAGING_SERVICE = getenv('TWILIO_CLEANING_REMINDER_MESSAGING_SERVICE')
TWILIO_CLEANING_POST_EVENT_FEEDBACK_MESSAGING_SERVICE = getenv('TWILIO_CLEANING_POST_EVENT_FEEDBACK_MESSAGING_SERVICE')
